services:
  mysql:
    image: mysql:8.0
    container_name: healthcare-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: medical_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - healthcare-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456789"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: healthcare-redis1
    restart: always
    ports:
      - "6379:6379"
    networks:
      healthcare-network:
        aliases:
          - redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-spring/HealthCARE-App-mrx-part4
      dockerfile: Dockerfile
    container_name: healthcare-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/medical_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
      JWT_SECRET: healthcareplussecretkeyhealthcareplussecretkey
      JWT_EXPIRATION: 86400000
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_CACHE_TYPE: redis
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - healthcare-network

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: healthcare-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - healthcare-network

volumes:
  mysql_data:

networks:
  healthcare-network:
    driver: bridge