spring.application.name=HealthCARE-App

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/medical_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456789}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

jwt.secret=${JWT_SECRET:healthcareplussecretkeyhealthcareplussecretkey}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:${REDIS_HOST:localhost}}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:${REDIS_PORT:6379}}
spring.cache.type=${SPRING_CACHE_TYPE:redis}

server.port=${PORT:8080}



